### PR TITLE
Use Hono SmartRouter instead of RegExpRouter

### PR DESCRIPTION
**Pull request by aquapi**
RegExp is much slower in JSC than in V8

### CODE REVIEW

**Comment by SaltyAom** [comment]
@yusukebe can you confirm?

**Comment by yusukebe** [comment]
Hi @aquapi and thanks @SaltyAom for pinging.

I think this PR should be closed.

I don't know if RegExp is V8 slower than JSC, but in this case, `SmartRouter` will choose `RegExpRouter`. It is better to specify `RegExpRouter` because `SmartRouter` has an overhead at the very first access.

**Comment by aquapi** [comment]
@yusukebe Is TrieRouter faster in this case?

**Comment by yusukebe** [comment]
@aquapi 

No. `TrieRouter` is slower than `RegExpRouter`.

> Because on my machine Hono was slower if `RegExpRouter` is manually selected.

It's weird, but on my machine, `RegExpRouter` is faster than `TrieRouter`.

**Pull request closed without merging**
